# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_F1(object):
    def setupUi(self, F1):
        F1.setObjectName("F1")
        F1.resize(900, 585)
        F1.setMinimumSize(QtCore.QSize(900, 585))
        F1.setMaximumSize(QtCore.QSize(900, 585))
        self.OB2 = QtWidgets.QLabel(F1)
        self.OB2.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB2.setText("")
        self.OB2.setPixmap(QtGui.QPixmap("scr2.jpg"))
        self.OB2.setScaledContents(True)
        self.OB2.setObjectName("OB2")
        self.OB3 = QtWidgets.QLabel(F1)
        self.OB3.setGeometry(QtCore.QRect(300, 10, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.OB3.setFont(font)
        self.OB3.setObjectName("OB3")
        self.OB4 = QtWidgets.QPushButton(F1)
        self.OB4.setGeometry(QtCore.QRect(740, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB4.setFont(font)
        self.OB4.setObjectName("OB4")
        self.OB5 = QtWidgets.QPushButton(F1)
        self.OB5.setGeometry(QtCore.QRect(120, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB5.setFont(font)
        self.OB5.setObjectName("OB5")
        self.OB6 = QtWidgets.QToolButton(F1)
        self.OB6.setGeometry(QtCore.QRect(50, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB6.setFont(font)
        self.OB6.setObjectName("OB6")
        self.OB1 = QtWidgets.QComboBox(F1)
        self.OB1.setGeometry(QtCore.QRect(590, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB1.setFont(font)
        self.OB1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.OB1.setObjectName("OB1")
        self.OB1.addItem("")
        self.OB1.addItem("")
        self.OB1.addItem("")
        self.OB1.addItem("")

        self.retranslateUi(F1)
        QtCore.QMetaObject.connectSlotsByName(F1)

    def retranslateUi(self, F1):
        _translate = QtCore.QCoreApplication.translate
        F1.setWindowTitle(_translate("F1", "Form"))
        self.OB3.setText(_translate("F1", "<html><head/><body><p align=\"center\">فروشگاه اینترنتی گل برگ</p></body></html>"))
        self.OB4.setText(_translate("F1", "خانه"))
        self.OB5.setText(_translate("F1", "ایجاد/ورود به حساب"))
        self.OB6.setText(_translate("F1", "ارتباط با ما"))
        self.OB1.setItemText(0, _translate("F1", "دسته بندی محصولات"))
        self.OB1.setItemText(1, _translate("F1", "پوشاک "))
        self.OB1.setItemText(2, _translate("F1", "ارایشی بهداشتی "))
        self.OB1.setItemText(3, _translate("F1", "لوازم خانگی"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F1 = QtWidgets.QWidget()
    ui = Ui_F1()
    ui.setupUi(F1)
    F1.show()
    sys.exit(app.exec_())
