# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F12.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_F12(object):
    def setupUi(self, F12):
        F12.setObjectName("F12")
        F12.resize(434, 536)
        F12.setMinimumSize(QtCore.QSize(434, 536))
        F12.setMaximumSize(QtCore.QSize(434, 536))
        F12.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.239, y1:0.238636, x2:1, y2:1, stop:0 rgba(127, 225, 43, 255), stop:1 rgba(255, 255, 255, 255))")
        self.pic_lbl = QtWidgets.QLabel(F12)
        self.pic_lbl.setGeometry(QtCore.QRect(105, 20, 220, 220))
        self.pic_lbl.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.505682, radius:0.466655, fx:0.5, fy:0.511364, stop:0 rgba(243, 205, 29, 217), stop:1 rgba(255, 255, 255, 255));\n"
        "border-radius:circle\n"
        "")
        self.pic_lbl.setText("")
        self.pic_lbl.setObjectName("pic_lbl")
        self.name_lbl = QtWidgets.QLabel(F12)
        self.name_lbl.setGeometry(QtCore.QRect(240, 270, 111, 51))
        self.name_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.name_lbl.setText("")
        self.name_lbl.setObjectName("name_lbl")
        self.num_lbl = QtWidgets.QLabel(F12)
        self.num_lbl.setGeometry(QtCore.QRect(240, 370, 111, 51))
        self.num_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.num_lbl.setText("")
        self.num_lbl.setObjectName("num_lbl")
        self.prc_lbl = QtWidgets.QLabel(F12)
        self.prc_lbl.setGeometry(QtCore.QRect(40, 270, 111, 51))
        self.prc_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.prc_lbl.setText("")
        self.prc_lbl.setObjectName("prc_lbl")
        self.id_lbl = QtWidgets.QLabel(F12)
        self.id_lbl.setGeometry(QtCore.QRect(40, 370, 111, 51))
        self.id_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.id_lbl.setText("")
        self.id_lbl.setObjectName("id_lbl")
        self.add_btn = QtWidgets.QPushButton(F12)
        self.add_btn.setGeometry(QtCore.QRect(130, 450, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_btn.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.add_btn.setObjectName("add_btn")
        self.tprc_lbl = QtWidgets.QLabel(F12)
        self.tprc_lbl.setGeometry(QtCore.QRect(160, 270, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tprc_lbl.setFont(font)
        self.tprc_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tprc_lbl.setObjectName("tprc_lbl")
        self.tid_lbl = QtWidgets.QLabel(F12)
        self.tid_lbl.setGeometry(QtCore.QRect(160, 370, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tid_lbl.setFont(font)
        self.tid_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tid_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tid_lbl.setObjectName("tid_lbl")
        self.tnum_lbl = QtWidgets.QLabel(F12)
        self.tnum_lbl.setGeometry(QtCore.QRect(360, 370, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tnum_lbl.setFont(font)
        self.tnum_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tnum_lbl.setObjectName("tnum_lbl")
        self.tname_lbl = QtWidgets.QLabel(F12)
        self.tname_lbl.setGeometry(QtCore.QRect(360, 270, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tname_lbl.setFont(font)
        self.tname_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tname_lbl.setObjectName("tname_lbl")

        self.retranslateUi(F12)
        QtCore.QMetaObject.connectSlotsByName(F12)

    def retranslateUi(self, F12):
        _translate = QtCore.QCoreApplication.translate
        F12.setWindowTitle(_translate("F12", "Form"))
        self.add_btn.setText(_translate("F12", "افزودن به سبد خرید"))
        self.tprc_lbl.setText(_translate("F12", "  قیمت:"))
        self.tid_lbl.setText(_translate("F12", " شناسه:"))
        self.tnum_lbl.setText(_translate("F12", "  تعداد:"))
        self.tname_lbl.setText(_translate("F12", "  نام:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F12 = QtWidgets.QWidget()
    ui = Ui_F12()
    ui.setupUi(F12)
    F12.show()
    sys.exit(app.exec_())
