# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_F14(object):
    def setupUi(self, F14):
        F14.setObjectName("F14")
        F14.resize(434, 536)
        F14.setMinimumSize(QtCore.QSize(434, 536))
        F14.setMaximumSize(QtCore.QSize(434, 536))
        F14.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.239, y1:0.238636, x2:1, y2:1, stop:0 rgba(127, 225, 43, 255), stop:1 rgba(255, 255, 255, 255))")
        self.O51 = QtWidgets.QLabel(F14)
        self.O51.setGeometry(QtCore.QRect(105, 20, 220, 220))
        self.O51.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.505682, radius:0.466655, fx:0.5, fy:0.511364, stop:0 rgba(243, 205, 29, 217), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:circle\n"
"")
        self.O51.setText("")
        self.O51.setObjectName("O51")
        self.O52 = QtWidgets.QLabel(F14)
        self.O52.setGeometry(QtCore.QRect(280, 300, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O52.setFont(font)
        self.O52.setStyleSheet("background-color:rgb(171, 255, 181);\n"
"border-radius:12px")
        self.O52.setObjectName("O52")
        self.O53 = QtWidgets.QLabel(F14)
        self.O53.setGeometry(QtCore.QRect(260, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O53.setFont(font)
        self.O53.setStyleSheet("background-color:rgb(171, 255, 181);\n"
"border-radius:12px")
        self.O53.setObjectName("O53")
        self.O56 = QtWidgets.QPushButton(F14)
        self.O56.setGeometry(QtCore.QRect(190, 470, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O56.setFont(font)
        self.O56.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.O56.setObjectName("O56")
        self.O54 = QtWidgets.QLineEdit(F14)
        self.O54.setGeometry(QtCore.QRect(110, 305, 113, 31))
        self.O54.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.O54.setObjectName("O54")
        self.O55 = QtWidgets.QLineEdit(F14)
        self.O55.setGeometry(QtCore.QRect(110, 395, 113, 31))
        self.O55.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.O55.setObjectName("O55")

        self.retranslateUi(F14)
        QtCore.QMetaObject.connectSlotsByName(F14)

    def retranslateUi(self, F14):
        _translate = QtCore.QCoreApplication.translate
        F14.setWindowTitle(_translate("F14", "Form"))
        self.O52.setText(_translate("F14", "قیمت:"))
        self.O53.setText(_translate("F14", "تعداد موجود:"))
        self.O56.setText(_translate("F14", "ثبت تغییرات"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F14 = QtWidgets.QWidget()
    ui = Ui_F14()
    ui.setupUi(F14)
    F14.show()
    sys.exit(app.exec_())
