# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'F4.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.0
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_F4(object):
#     def setupUi(self, F4):
#         F4.setObjectName("F4")
#         F4.resize(900, 585)
#         F4.setMinimumSize(QtCore.QSize(900, 585))
#         F4.setMaximumSize(QtCore.QSize(900, 585))
#         self.OB20 = QtWidgets.QLabel(F4)
#         self.OB20.setGeometry(QtCore.QRect(0, 0, 900, 585))
#         self.OB20.setText("")
#         self.OB20.setPixmap(QtGui.QPixmap("scr1.jpg"))
#         self.OB20.setScaledContents(True)
#         self.OB20.setObjectName("OB20")
#         self.OB21 = QtWidgets.QLabel(F4)
#         self.OB21.setGeometry(QtCore.QRect(350, 180, 181, 51))
#         font = QtGui.QFont()
#         font.setFamily("Urdu Typesetting")
#         font.setPointSize(24)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB21.setFont(font)
#         self.OB21.setObjectName("OB21")
#         self.OB22 = QtWidgets.QLabel(F4)
#         self.OB22.setGeometry(QtCore.QRect(590, 270, 71, 16))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB22.setFont(font)
#         self.OB22.setObjectName("OB22")
#         self.OB23 = QtWidgets.QLabel(F4)
#         self.OB23.setGeometry(QtCore.QRect(600, 310, 61, 16))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB23.setFont(font)
#         self.OB23.setObjectName("OB23")
#         self.OB24 = QtWidgets.QLabel(F4)
#         self.OB24.setGeometry(QtCore.QRect(585, 350, 81, 16))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB24.setFont(font)
#         self.OB24.setObjectName("OB24")
#         self.OB25 = QtWidgets.QLabel(F4)
#         self.OB25.setGeometry(QtCore.QRect(570, 390, 101, 16))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB25.setFont(font)
#         self.OB25.setObjectName("OB25")
#         self.OB26 = QtWidgets.QLineEdit(F4)
#         self.OB26.setGeometry(QtCore.QRect(370, 270, 161, 20))
#         self.OB26.setObjectName("OB26")
#         self.OB27 = QtWidgets.QLineEdit(F4)
#         self.OB27.setGeometry(QtCore.QRect(370, 310, 161, 20))
#         self.OB27.setEchoMode(QtWidgets.QLineEdit.Password)
#         self.OB27.setObjectName("OB27")
#         self.OB28 = QtWidgets.QLineEdit(F4)
#         self.OB28.setGeometry(QtCore.QRect(370, 350, 161, 20))
#         self.OB28.setEchoMode(QtWidgets.QLineEdit.Password)
#         self.OB28.setObjectName("OB28")
#         self.OB29 = QtWidgets.QLineEdit(F4)
#         self.OB29.setGeometry(QtCore.QRect(370, 390, 161, 20))
#         self.OB29.setObjectName("OB29")
#         self.OB30 = QtWidgets.QPushButton(F4)
#         self.OB30.setGeometry(QtCore.QRect(390, 490, 111, 61))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(18)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB30.setFont(font)
#         self.OB30.setStyleSheet("background-color: rgb(139, 179, 158);\n"
# "border-radius:20px")
#         self.OB30.setObjectName("OB30")
#         self.OB31 = QtWidgets.QRadioButton(F4)
#         self.OB31.setGeometry(QtCore.QRect(370, 450, 82, 17))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB31.setFont(font)
#         self.OB31.setObjectName("OB31")
#         self.OB32 = QtWidgets.QRadioButton(F4)
#         self.OB32.setGeometry(QtCore.QRect(460, 450, 82, 17))
#         font = QtGui.QFont()
#         font.setFamily("Calibri")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.OB32.setFont(font)
#         self.OB32.setObjectName("OB32")
#
#         self.retranslateUi(F4)
#         QtCore.QMetaObject.connectSlotsByName(F4)
#
#     def retranslateUi(self, F4):
#         _translate = QtCore.QCoreApplication.translate
#         F4.setWindowTitle(_translate("F4", "Form"))
#         self.OB21.setText(_translate("F4", "ایجاد حساب کاربری"))
#         self.OB22.setText(_translate("F4", "نام کاربری:"))
#         self.OB23.setText(_translate("F4", "گذرواژه:"))
#         self.OB24.setText(_translate("F4", "تایید گذرواژه:"))
#         self.OB25.setText(_translate("F4", "پست الکترونیکی:"))
#         self.OB30.setText(_translate("F4", "تایید"))
#         self.OB31.setText(_translate("F4", "خریدار"))
#         self.OB32.setText(_translate("F4", "فروشنده"))
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     F4 = QtWidgets.QWidget()
#     ui = Ui_F4()
#     ui.setupUi(F4)
#     F4.show()
#     sys.exit(app.exec_())
# # from PyQt5.QtWidgets import *
# # import sys
# #
# # class Window(QWidget):
# #     def __init__(self):
# #         QWidget.__init__(self)
# #         layout = QGridLayout()
# #         self.setLayout(layout)
# #
# #         radiobutton = QRadioButton("Australia")
# #         radiobutton.setChecked(True)
# #         radiobutton.country = "Australia"
# #         radiobutton.toggled.connect(self.onClicked)
# #         layout.addWidget(radiobutton, 0, 0)
# #
# #         radiobutton = QRadioButton("China")
# #         radiobutton.country = "China"
# #         radiobutton.toggled.connect(self.onClicked)
# #         layout.addWidget(radiobutton, 0, 1)
# #
# #         radiobutton = QRadioButton("Japan")
# #         radiobutton.country = "Japan"
# #         radiobutton.toggled.connect(self.onClicked)
# #         layout.addWidget(radiobutton, 0, 2)
# #
# #     def onClicked(self):
# #         radioButton = self.sender()
# #         if radioButton.isChecked():
# #             print("Country is %s" % (radioButton.country))
# #
# # app = QApplication(sys.argv)
# # screen = Window()
# # screen.show()
# # sys.exit(app.exec_())
import sys
from PyQt5.QtWidgets import QApplication, QDialog, QFormLayout
from PyQt5.QtWidgets import (QPushButton, QLineEdit)

class Form(QDialog):
    def __init__(self, parent=None):
        super(Form, self).__init__(parent)

        self.le = QLineEdit()
        self.le.setObjectName("host")
        self.le.setText("Host")

        self.pb = QPushButton()
        self.pb.setObjectName("connect")
        self.pb.setText("Connect")
        self.pb.clicked.connect(self.button_click)

        layout = QFormLayout()
        layout.addWidget(self.le)
        layout.addWidget(self.pb)
        self.setLayout(layout)

        self.setWindowTitle("Learning")

    def button_click(self):
        # shost is a QString object
        shost = self.le.text()
        print (shost)


app = QApplication(sys.argv)
form = Form()
form.show()
app.exec_()