# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F7.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_F7(object):
    def setupUi(self, F7):
        F7.setObjectName("F7")
        F7.resize(900, 585)
        F7.setMinimumSize(QtCore.QSize(900, 585))
        F7.setMaximumSize(QtCore.QSize(900, 585))
        self.pinfo = QtWidgets.QLabel(F7)
        self.pinfo.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.pinfo.setMinimumSize(QtCore.QSize(900, 585))
        self.pinfo.setMaximumSize(QtCore.QSize(900, 585))
        self.pinfo.setText("")
        self.pinfo.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.pinfo.setScaledContents(True)
        self.pinfo.setObjectName("pinfo")
        self.tifo = QtWidgets.QLabel(F7)
        self.tifo.setGeometry(QtCore.QRect(380, 160, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.tifo.setFont(font)
        self.tifo.setObjectName("tifo")
        self.telfo = QtWidgets.QLabel(F7)
        self.telfo.setGeometry(QtCore.QRect(670, 300, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.telfo.setFont(font)
        self.telfo.setObjectName("telfo")
        self.posfo = QtWidgets.QLabel(F7)
        self.posfo.setGeometry(QtCore.QRect(510, 350, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.posfo.setFont(font)
        self.posfo.setObjectName("posfo")
        self.addfo = QtWidgets.QLabel(F7)
        self.addfo.setGeometry(QtCore.QRect(450, 400, 421, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addfo.setFont(font)
        self.addfo.setObjectName("addfo")
        self.Hbtn = QtWidgets.QPushButton(F7)
        self.Hbtn.setGeometry(QtCore.QRect(40, 510, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Hbtn.setFont(font)
        self.Hbtn.setObjectName("Hbtn")

        self.retranslateUi(F7)
        QtCore.QMetaObject.connectSlotsByName(F7)

    def retranslateUi(self, F7):
        _translate = QtCore.QCoreApplication.translate
        F7.setWindowTitle(_translate("F7", "Form"))
        self.tifo.setText(_translate("F7", " ارتباط با ما"))
        self.telfo.setText(_translate("F7", "تلفن: 02188442112"))
        self.posfo.setText(_translate("F7", "پست الکترونیکی: golbarg.shop@yahoo.com"))
        self.addfo.setText(_translate("F7", "  آدرس: خیابان نلسون ماندلا - نرسیده به چهارراه جهان کودک \n"
" ساختمان امیرپرویز - طبقه 9 - واحد 54"))
        self.Hbtn.setText(_translate("F7", "بازگشت به خانه"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F7 = QtWidgets.QWidget()
    ui = Ui_F7()
    ui.setupUi(F7)
    F7.show()
    sys.exit(app.exec_())
