# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F8.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_F8(object):
    def setupUi(self, F8):
        F8.setObjectName("F8")
        F8.resize(900, 585)
        F8.setMinimumSize(QtCore.QSize(900, 585))
        F8.setMaximumSize(QtCore.QSize(900, 585))
        self.b_lbl = QtWidgets.QLabel(F8)
        self.b_lbl.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.b_lbl.setMinimumSize(QtCore.QSize(900, 585))
        self.b_lbl.setMaximumSize(QtCore.QSize(900, 585))
        self.b_lbl.setText("")
        self.b_lbl.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.b_lbl.setScaledContents(True)
        self.b_lbl.setObjectName("b_lbl")
        self.add_btn = QtWidgets.QPushButton(F8)
        self.add_btn.setGeometry(QtCore.QRect(630, 150, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("")
        self.add_btn.setObjectName("add_btn")
        self.label = QtWidgets.QLabel(F8)
        self.label.setGeometry(QtCore.QRect(670, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.h_btn = QtWidgets.QPushButton(F8)
        self.h_btn.setGeometry(QtCore.QRect(90, 150, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.h_btn.setFont(font)
        self.h_btn.setObjectName("h_btn")
        self.lst = QtWidgets.QListView(F8)
        self.lst.setGeometry(QtCore.QRect(90, 210, 721, 301))
        self.lst.setObjectName("lst")
        self.ed_btn_2 = QtWidgets.QPushButton(F8)
        self.ed_btn_2.setGeometry(QtCore.QRect(390, 150, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ed_btn_2.setFont(font)
        self.ed_btn_2.setObjectName("ed_btn_2")

        self.retranslateUi(F8)
        QtCore.QMetaObject.connectSlotsByName(F8)

    def retranslateUi(self, F8):
        _translate = QtCore.QCoreApplication.translate
        F8.setWindowTitle(_translate("F8", "Form"))
        self.add_btn.setText(_translate("F8", "+"))
        self.label.setText(_translate("F8", "ثبت محصول جدید"))
        self.h_btn.setText(_translate("F8", "بازگشت به خانه"))
        self.ed_btn_2.setText(_translate("F8", "ویرایش"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F8 = QtWidgets.QWidget()
    ui = Ui_F8()
    ui.setupUi(F8)
    F8.show()
    sys.exit(app.exec_())
