# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F9.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_F9(object):
    def setupUi(self, F9):
        F9.setObjectName("F9")
        F9.resize(340, 505)
        F9.setStyleSheet("background:qlineargradient(spread:pad, x1:0.239, y1:0.238636, x2:1, y2:1, stop:0 rgba(127, 225, 43, 255), stop:1 rgba(255, 255, 255, 255))")
        self.pi_lbl = QtWidgets.QLabel(F9)
        self.pi_lbl.setGeometry(QtCore.QRect(75, 20, 200, 180))
        self.pi_lbl.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.505682, radius:0.466655, fx:0.5, fy:0.511364, stop:0 rgba(243, 205, 29, 217), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.pi_lbl.setText("")
        self.pi_lbl.setScaledContents(True)
        self.pi_lbl.setObjectName("pi_lbl")
        self.up_btn = QtWidgets.QPushButton(F9)
        self.up_btn.setGeometry(QtCore.QRect(120, 220, 101, 30))
        self.up_btn.setStyleSheet("background:None")
        self.up_btn.setObjectName("up_btn")
        self.up_btn.clicked.connect(self.getImage)
        self.lineEdit = QtWidgets.QLineEdit(F9)
        self.lineEdit.setGeometry(QtCore.QRect(30, 265, 211, 28))
        self.lineEdit.setStyleSheet("background:None")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(F9)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 310, 211, 28))
        self.lineEdit_2.setStyleSheet("background:None")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.con_btn = QtWidgets.QPushButton(F9)
        self.con_btn.setGeometry(QtCore.QRect(120, 450, 101, 31))
        self.con_btn.setStyleSheet("background:None")
        self.con_btn.setObjectName("con_btn")
        self.g_name = QtWidgets.QLabel(F9)
        self.g_name.setGeometry(QtCore.QRect(243, 270, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.g_name.setFont(font)
        self.g_name.setStyleSheet("background:None")
        self.g_name.setObjectName("g_name")
        self.prc = QtWidgets.QLabel(F9)
        self.prc.setGeometry(QtCore.QRect(240, 310, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.prc.setFont(font)
        self.prc.setStyleSheet("background:None")
        self.prc.setObjectName("prc")
        self.prc_2 = QtWidgets.QLabel(F9)
        self.prc_2.setGeometry(QtCore.QRect(240, 360, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.prc_2.setFont(font)
        self.prc_2.setStyleSheet("background:None")
        self.prc_2.setObjectName("prc_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(F9)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 355, 211, 28))
        self.lineEdit_3.setStyleSheet("background:None")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(F9)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 400, 171, 28))
        self.lineEdit_4.setStyleSheet("background:None")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.prc_3 = QtWidgets.QLabel(F9)
        self.prc_3.setGeometry(QtCore.QRect(240, 405, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.prc_3.setFont(font)
        self.prc_3.setStyleSheet("background:None")
        self.prc_3.setObjectName("prc_3")
        self.pr_lbl = QtWidgets.QLabel(F9)
        self.pr_lbl.setGeometry(QtCore.QRect(36, 399, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pr_lbl.setFont(font)
        self.pr_lbl.setStyleSheet("background-color:None")
        self.pr_lbl.setObjectName("pr_lbl")

        self.retranslateUi(F9)
        QtCore.QMetaObject.connectSlotsByName(F9)

    def retranslateUi(self, F9):
        _translate = QtCore.QCoreApplication.translate
        F9.setWindowTitle(_translate("F9", "Form"))
        self.up_btn.setText(_translate("F9", "آپلود عکس"))
        self.con_btn.setText(_translate("F9", "ثبت"))
        self.g_name.setText(_translate("F9", "نام محصول:"))
        self.prc.setText(_translate("F9", "قیمت:"))
        self.prc_2.setText(_translate("F9", "موجودی محصول:"))
        self.prc_3.setText(_translate("F9", "شناسه محصول:"))
        self.pr_lbl.setText(_translate("F9", "PR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F9 = QtWidgets.QWidget()
    ui = Ui_F9()
    ui.setupUi(F9)
    F9.show()
    sys.exit(app.exec_())
