from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
import sqlite3

conn = sqlite3.connect('database.db')
curs = conn.cursor()

# curs.execute("""
#             CREATE TABLE data (user_n text, pass integer, email text, typ integer)
# """)

class Ui_F1(object):
    def setupUi(self, F1):
        self.F1 = F1
        F1.setObjectName("F1")
        F1.resize(900, 585)
        F1.setMinimumSize(QtCore.QSize(900, 585))
        F1.setMaximumSize(QtCore.QSize(900, 585))
        self.OB2 = QtWidgets.QLabel(F1)
        self.OB2.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB2.setText("")
        self.OB2.setPixmap(QtGui.QPixmap("scr2.jpg"))
        self.OB2.setScaledContents(True)
        self.OB2.setObjectName("OB2")
        self.OB3 = QtWidgets.QLabel(F1)
        self.OB3.setGeometry(QtCore.QRect(300, 10, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.OB3.setFont(font)
        self.OB3.setObjectName("OB3")
        self.OB4 = QtWidgets.QPushButton(F1)
        self.OB4.setGeometry(QtCore.QRect(740, 120, 81, 31))
        self.OB4.clicked.connect(self.swicthtoF1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB4.setFont(font)
        self.OB4.setObjectName("OB4")
        self.OB5 = QtWidgets.QPushButton(F1)
        self.OB5.setGeometry(QtCore.QRect(120, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB5.setFont(font)
        self.OB5.setObjectName("OB5")
        self.OB5.clicked.connect(self.swicthtoF2)
        self.OB6 = QtWidgets.QToolButton(F1)
        self.OB6.setGeometry(QtCore.QRect(50, 120, 81, 31))
        self.OB6.clicked.connect(self.swicthtoF7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB6.setFont(font)
        self.OB6.setObjectName("OB6")
        self.OB1 = QtWidgets.QComboBox(F1)
        self.OB1.setGeometry(QtCore.QRect(590, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB1.setFont(font)
        self.OB1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.OB1.setObjectName("OB1")
        self.OB1.addItem("")
        self.OB1.addItem("")
        self.OB1.addItem("")
        self.OB1.addItem("")
        self.lst = QtWidgets.QListWidget(F1)
        self.lst.setGeometry(QtCore.QRect(90, 210, 721, 301))
        self.lst.setObjectName("lst")
        self.fetchdata()

        self.retranslateUi(F1)
        QtCore.QMetaObject.connectSlotsByName(F1)

    def fetchdata(self):
        curs.execute("SELECT good_n FROM goods")
        names = curs.fetchall()
        curs.execute("SELECT price FROM goods")
        prices = curs.fetchall()
        curs.execute("SELECT id FROM goods")
        ids = curs.fetchall()
        x = 0
        for i in ids:
            row = self.lst.currentRow()
            self.lst.insertItem(row, f"{i[0]}  ==>  {names[x][0]} ***** {prices[x][0]}تومان")
            x += 1

    def swicthtoF2(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F2()
        self.ui.setupUi(self.window)
        self.F1.close()
        self.window.show()

    def swicthtoF1(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F1()
        self.ui.setupUi(self.window)
        self.F1.close()
        self.window.show()

    def swicthtoF7(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F7()
        self.ui.setupUi(self.window)
        self.F1.close()
        self.window.show()

    def retranslateUi(self, F1):
        _translate = QtCore.QCoreApplication.translate
        F1.setWindowTitle(_translate("F1", "Form"))
        self.OB3.setText(_translate("F1", "<html><head/><body><p align=\"center\">فروشگاه اینترنتی گل برگ</p></body></html>"))
        self.OB4.setText(_translate("F1", "خانه"))
        self.OB5.setText(_translate("F1", "ایجاد/ورود به حساب"))
        self.OB6.setText(_translate("F1", "ارتباط با ما"))
        self.OB1.setItemText(0, _translate("F1", "دسته بندی محصولات"))
        self.OB1.setItemText(1, _translate("F1", "پوشاک "))
        self.OB1.setItemText(2, _translate("F1", "آرایشی بهداشتی "))
        self.OB1.setItemText(3, _translate("F1", "لوازم خانگی"))

class Ui_F2(object):
    def setupUi(self, F2):
        self.F2 = F2
        F2.setObjectName("F2")
        F2.resize(900, 585)
        F2.setMinimumSize(QtCore.QSize(900, 585))
        F2.setMaximumSize(QtCore.QSize(900, 585))
        F2.setStyleSheet("background-color: rgb(245, 149, 229);\n"
        "background-color: rgb(255, 198, 248);")
        self.OB10 = QtWidgets.QLabel(F2)
        self.OB10.setGeometry(QtCore.QRect(350, 190, 221, 131))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.OB10.setFont(font)
        self.OB10.setStyleSheet("background-color: None;")
        self.OB10.setObjectName("OB10")
        self.OB8 = QtWidgets.QPushButton(F2)
        self.OB8.setGeometry(QtCore.QRect(410, 330, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.OB8.setFont(font)
        self.OB8.setStyleSheet("background-color:   rgb(139, 179, 158);\n"
        "border-radius:20px")
        self.OB8.setObjectName("OB8")
        self.OB8.clicked.connect(self.swicthtoF3)
        self.OB9 = QtWidgets.QPushButton(F2)
        self.OB9.setGeometry(QtCore.QRect(410, 430, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.OB9.setFont(font)
        self.OB9.setStyleSheet("background-color: rgb(139, 179, 158);\n"
        "border-radius:20px")
        self.OB9.setObjectName("OB9")
        self.OB9.clicked.connect(self.swicthtoF4)
        self.OB7 = QtWidgets.QLabel(F2)
        self.OB7.setEnabled(True)
        self.OB7.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB7.setMouseTracking(False)
        self.OB7.setTabletTracking(False)
        self.OB7.setAutoFillBackground(False)
        self.OB7.setText("")
        self.OB7.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.OB7.setScaledContents(True)
        self.OB7.setObjectName("OB7")
        self.OB7.raise_()
        self.OB10.raise_()
        self.OB8.raise_()
        self.OB9.raise_()

        self.retranslateUi(F2)
        QtCore.QMetaObject.connectSlotsByName(F2)

    def swicthtoF4(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F4()
        self.ui.setupUi(self.window)
        self.F2.close()
        self.window.show()

    def swicthtoF3(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F3()
        self.ui.setupUi(self.window)
        self.F2.close()
        self.window.show()
    def retranslateUi(self, F2):
        _translate = QtCore.QCoreApplication.translate
        F2.setWindowTitle(_translate("F2", "Form"))
        self.OB10.setText(_translate("F2", "<html><head/><body><p><span style=\" font-size:28pt;\">فروشگاه اینترنتی گل برگ</span></p></body></html>"))
        self.OB8.setText(_translate("F2", "ورود"))
        self.OB9.setText(_translate("F2", "عضویت"))

class Ui_F3(object):
    def setupUi(self, F3):
        self.F3 = F3
        F3.setObjectName("F3")
        F3.resize(900, 585)
        F3.setMinimumSize(QtCore.QSize(900, 585))
        F3.setMaximumSize(QtCore.QSize(900, 585))
        F3.setStyleSheet("background-color: rgb(250,250,250)")
        self.OB14 = QtWidgets.QLabel(F3)
        self.OB14.setGeometry(QtCore.QRect(390, 160, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.OB14.setFont(font)
        self.OB14.setStyleSheet("background-color: None;\n"
        "color: rgb(22, 22, 0);")
        self.OB14.setObjectName("OB14")
        self.OB15 = QtWidgets.QLabel(F3)
        self.OB15.setGeometry(QtCore.QRect(590, 280, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB15.setFont(font)
        self.OB15.setStyleSheet("background-color: None")
        self.OB15.setObjectName("OB15")
        self.OB16 = QtWidgets.QLabel(F3)
        self.OB16.setGeometry(QtCore.QRect(600, 340, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB16.setFont(font)
        self.OB16.setStyleSheet("background-color: None")
        self.OB16.setObjectName("OB16")
        self.OB11 = QtWidgets.QLineEdit(F3)
        self.OB11.setGeometry(QtCore.QRect(380, 280, 181, 31))
        self.OB11.setObjectName("OB11")
        self.OB12 = QtWidgets.QLineEdit(F3)
        self.OB12.setGeometry(QtCore.QRect(380, 340, 181, 31))
        self.OB12.setEchoMode(QtWidgets.QLineEdit.Password)
        self.OB12.setObjectName("OB12")
        self.OB13 = QtWidgets.QLabel(F3)
        self.OB13.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB13.setText("")
        self.OB13.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.OB13.setScaledContents(True)
        self.OB13.setObjectName("OB13")
        self.OB17 = QtWidgets.QPushButton(F3)
        self.OB17.setGeometry(QtCore.QRect(410, 430, 111, 61))
        self.OB17.clicked.connect(self.checking)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.OB17.setFont(font)
        self.OB17.setStyleSheet("background-color: rgb(139, 179, 158);\n"
        "border-radius:20px")
        self.OB17.setObjectName("OB17")
        self.OB13.raise_()
        self.OB14.raise_()
        self.OB15.raise_()
        self.OB16.raise_()
        self.OB11.raise_()
        self.OB12.raise_()
        self.OB17.raise_()

        self.retranslateUi(F3)
        QtCore.QMetaObject.connectSlotsByName(F3)

    def checking(self):
        curs.execute("SELECT * FROM data")

        data_lst = curs.fetchall()
        for i in range (len(data_lst)):
            user_t, pass_t, t = data_lst[i][0], data_lst[i][1], data_lst[i][3]
            user_name = self.OB11.text()
            pass_word = self.OB12.text()
            if user_name == user_t and str(pass_t) == pass_word and t == 1:
                self.switchtoF5()
            if user_name == user_t and str(pass_t) == pass_word and t == 0:
                self.switchtoF6()

    def switchtoF5(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F5()
        self.ui.setupUi(self.window)
        self.F3.close()
        self.window.show()

    def switchtoF6(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F6()
        self.ui.setupUi(self.window)
        self.F3.close()
        self.window.show()

    def retranslateUi(self, F3):
        _translate = QtCore.QCoreApplication.translate
        F3.setWindowTitle(_translate("F3", "Form"))
        self.OB14.setText(_translate("F3", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">ورود به حساب کاربری</span></p></body></html>"))
        self.OB15.setText(_translate("F3", "<html><head/><body><p align=\"right\">:نام کاربری</p></body></html>"))
        self.OB16.setText(_translate("F3", "<html><head/><body><p align=\"right\">:گذرواژه</p></body></html>"))
        self.OB17.setText(_translate("F3", "ورود"))

class Ui_F4(object):
    def setupUi(self, F4):
        self.F4 = F4
        F4.setObjectName("F4")
        F4.resize(900, 585)
        F4.setMinimumSize(QtCore.QSize(900, 585))
        F4.setMaximumSize(QtCore.QSize(900, 585))
        self.OB20 = QtWidgets.QLabel(F4)
        self.OB20.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB20.setText("")
        self.OB20.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.OB20.setScaledContents(True)
        self.OB20.setObjectName("OB20")
        self.OB21 = QtWidgets.QLabel(F4)
        self.OB21.setGeometry(QtCore.QRect(350, 180, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.OB21.setFont(font)
        self.OB21.setObjectName("OB21")
        self.OB22 = QtWidgets.QLabel(F4)
        self.OB22.setGeometry(QtCore.QRect(590, 270, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB22.setFont(font)
        self.OB22.setObjectName("OB22")
        self.OB23 = QtWidgets.QLabel(F4)
        self.OB23.setGeometry(QtCore.QRect(600, 310, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB23.setFont(font)
        self.OB23.setObjectName("OB23")
        self.OB24 = QtWidgets.QLabel(F4)
        self.OB24.setGeometry(QtCore.QRect(585, 350, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB24.setFont(font)
        self.OB24.setObjectName("OB24")
        self.OB25 = QtWidgets.QLabel(F4)
        self.OB25.setGeometry(QtCore.QRect(570, 390, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB25.setFont(font)
        self.OB25.setObjectName("OB25")
        self.OB26 = QtWidgets.QLineEdit(F4)
        self.OB26.setGeometry(QtCore.QRect(370, 270, 161, 20))
        self.OB26.setObjectName("OB26")
        self.OB27 = QtWidgets.QLineEdit(F4)
        self.OB27.setGeometry(QtCore.QRect(370, 310, 161, 20))
        self.OB27.setEchoMode(QtWidgets.QLineEdit.Password)
        self.OB27.setObjectName("OB27")
        self.OB28 = QtWidgets.QLineEdit(F4)
        self.OB28.setGeometry(QtCore.QRect(370, 350, 161, 20))
        self.OB28.setEchoMode(QtWidgets.QLineEdit.Password)
        self.OB28.setObjectName("OB28")
        self.OB29 = QtWidgets.QLineEdit(F4)
        self.OB29.setGeometry(QtCore.QRect(370, 390, 161, 20))
        self.OB29.setObjectName("OB29")
        self.OB30 = QtWidgets.QPushButton(F4)
        self.OB30.setGeometry(QtCore.QRect(390, 490, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.OB30.clicked.connect(lambda: self.con(self.OB31.isChecked(), self.OB32))
        self.OB30.setFont(font)
        self.OB30.setStyleSheet("background-color: rgb(139, 179, 158);\n"
        "border-radius:20px")
        self.OB30.setObjectName("OB30")
        self.OB31 = QtWidgets.QRadioButton(F4)
        self.OB31.setGeometry(QtCore.QRect(370, 450, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB31.setFont(font)
        self.OB31.setObjectName("OB31")
        self.OB32 = QtWidgets.QRadioButton(F4)
        self.OB32.setGeometry(QtCore.QRect(460, 450, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB32.setFont(font)
        self.OB32.setObjectName("OB32")

        self.retranslateUi(F4)
        QtCore.QMetaObject.connectSlotsByName(F4)

    def con(self, cstmr, slr):
        user_n = self.OB26.text()
        pass_w = self.OB27.text()
        pass_w2 = self.OB28.text()
        email = self.OB29.text()
        if pass_w == pass_w2:
            if cstmr:
                x = 1
            else:
                x = 0
            curs.execute("INSERT INTO data(user_n, pass, email, typ) VALUES (?, ?, ?, ?)", (user_n, pass_w, email, x))
            conn.commit()
            self.switchtoF1()
        else:
            pass

    def switchtoF1(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F1()
        self.ui.setupUi(self.window)
        self.F4.close()
        self.window.show()

    def retranslateUi(self, F4):
        _translate = QtCore.QCoreApplication.translate
        F4.setWindowTitle(_translate("F4", "Form"))
        self.OB21.setText(_translate("F4", "ایجاد حساب کاربری"))
        self.OB22.setText(_translate("F4", "نام کاربری:"))
        self.OB23.setText(_translate("F4", "گذرواژه:"))
        self.OB24.setText(_translate("F4", "تایید گذرواژه:"))
        self.OB25.setText(_translate("F4", "پست الکترونیکی:"))
        self.OB30.setText(_translate("F4", "تایید"))
        self.OB31.setText(_translate("F4", "خریدار"))
        self.OB32.setText(_translate("F4", "فروشنده"))

class Ui_F5(object):
    def setupUi(self, F5):
        self.F5 = F5
        F5.setObjectName("F5")
        F5.resize(900, 585)
        F5.setMinimumSize(QtCore.QSize(900, 585))
        F5.setMaximumSize(QtCore.QSize(900, 585))
        self.OB31 = QtWidgets.QComboBox(F5)
        self.OB31.setGeometry(QtCore.QRect(670, 180, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB31.setFont(font)
        self.OB31.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.OB31.setObjectName("OB31")
        self.OB31.addItem("")
        self.OB31.addItem("")
        self.OB31.addItem("")
        self.OB31.addItem("")
        self.OB31.addItem("")
        self.OB31.setItemText(4, "")
        self.OB36 = QtWidgets.QLabel(F5)
        self.OB36.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB36.setText("")
        self.OB36.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.OB36.setScaledContents(True)
        self.OB36.setObjectName("OB36")
        self.OB32 = QtWidgets.QPushButton(F5)
        self.OB32.setGeometry(QtCore.QRect(820, 180, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB32.setFont(font)
        self.OB32.setObjectName("OB32")
        self.OB33 = QtWidgets.QPushButton(F5)
        self.OB33.setGeometry(QtCore.QRect(150, 180, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB33.setFont(font)
        self.OB33.setObjectName("OB33")
        self.OB34 = QtWidgets.QPushButton(F5)
        self.OB34.setGeometry(QtCore.QRect(54, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB34.setFont(font)
        self.OB34.setObjectName("OB34")
        self.OB35 = QtWidgets.QPushButton(F5)
        self.OB35.setGeometry(QtCore.QRect(220, 180, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB35.setFont(font)
        self.OB35.setObjectName("OB35")
        self.OB37 = QtWidgets.QPushButton(F5)
        self.OB37.setGeometry(QtCore.QRect(290, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB37.setFont(font)
        self.OB37.setObjectName("OB37")
        self.OB37.clicked.connect(self.switchtoF10)
        self.OB34.clicked.connect(self.switchtoF1)
        self.OB33.clicked.connect(self.switchtoF7)
        self.OB32.clicked.connect(self.myself)
        self.lst = QtWidgets.QListWidget(F5)
        self.lst.setGeometry(QtCore.QRect(60, 240, 801, 321))
        self.lst.setObjectName("lst")
        self.OB37_2 = QtWidgets.QPushButton(F5)
        self.OB37_2.setGeometry(QtCore.QRect(490, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB37_2.setFont(font)
        self.OB37_2.setObjectName("OB37_2")
        self.OB37_2.clicked.connect(self.pinfo)
        self.OB35.clicked.connect(self.switchtoF13)
        self.fetchdata()
        self.OB36.raise_()
        self.OB31.raise_()
        self.OB32.raise_()
        self.OB33.raise_()
        self.OB34.raise_()
        self.OB35.raise_()
        self.OB37.raise_()
        self.lst.raise_()
        self.OB37_2.raise_()

        self.retranslateUi(F5)
        QtCore.QMetaObject.connectSlotsByName(F5)

    def fetchdata(self):
        curs.execute("SELECT good_n FROM goods")
        names = curs.fetchall()
        curs.execute("SELECT price FROM goods")
        prices = curs.fetchall()
        curs.execute("SELECT id FROM goods")
        ids = curs.fetchall()
        curs.execute("SELECT num_of_p FROM goods")
        num = curs.fetchall()
        x = 0
        for i in ids:
            row = self.lst.currentRow()
            self.lst.insertItem(row, f"{i[0]}  ==>  {names[x][0]} ***** {prices[x][0]} ***** {num[x][0]}")
            x += 1

    def pinfo(self):
        self.info = self.lst.currentItem().text()
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F12()
        self.ui.setupUi(self.window)
        self.ui.catch(self.info)
        self.window.show()

    def switchtoF1(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F1()
        self.ui.setupUi(self.window)
        self.F5.close()
        self.window.show()

    def myself(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F5()
        self.ui.setupUi(self.window)
        self.F5.close()
        self.window.show()

    def switchtoF7(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F7()
        self.ui.setupUi(self.window)
        self.F5.close()
        self.window.show()

    def switchtoF10(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F10()
        self.ui.setupUi(self.window)
        self.F5.close()
        self.window.show()

    def switchtoF13(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F13()
        self.ui.setupUi(self.window)
        self.F5.close()
        self.window.show()

    def retranslateUi(self, F5):
        _translate = QtCore.QCoreApplication.translate
        F5.setWindowTitle(_translate("F5", "Form"))
        self.OB31.setItemText(0, _translate("F5", "دسته بندی محصولات"))
        self.OB31.setItemText(1, _translate("F5", "پوشاک"))
        self.OB31.setItemText(2, _translate("F5", "ارایشی بهداشتی "))
        self.OB31.setItemText(3, _translate("F5", "لوازم خانگی"))
        self.OB32.setText(_translate("F5", "خانه"))
        self.OB33.setText(_translate("F5", "تماس با ما"))
        self.OB34.setText(_translate("F5", "خروج از حساب"))
        self.OB35.setText(_translate("F5", "سبد خرید"))
        self.OB37.setText(_translate("F5", "کیف پول من"))
        self.OB37_2.setText(_translate("F5", "دیدن"))

class Ui_F6(object):
    def setupUi(self, F6):
        self.F6 = F6
        F6.setObjectName("F6")
        F6.resize(900, 585)
        F6.setMinimumSize(QtCore.QSize(900, 585))
        F6.setMaximumSize(QtCore.QSize(900, 585))
        self.OB38 = QtWidgets.QLabel(F6)
        self.OB38.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.OB38.setText("")
        self.OB38.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.OB38.setScaledContents(True)
        self.OB38.setObjectName("OB38")
        self.OB40 = QtWidgets.QPushButton(F6)
        self.OB40.setGeometry(QtCore.QRect(820, 180, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB40.setFont(font)
        self.OB40.setObjectName("OB40")
        self.OB41 = QtWidgets.QPushButton(F6)
        self.OB41.setGeometry(QtCore.QRect(795, 230, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB41.setFont(font)
        self.OB41.setObjectName("OB41")
        self.OB42 = QtWidgets.QPushButton(F6)
        self.OB42.setGeometry(QtCore.QRect(410, 180, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB42.setFont(font)
        self.OB42.setObjectName("OB42")
        self.OB42.clicked.connect(self.switchtoF8)
        self.OB43 = QtWidgets.QPushButton(F6)
        self.OB43.setGeometry(QtCore.QRect(660, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB43.setFont(font)
        self.OB43.setObjectName("OB43")
        self.OB44 = QtWidgets.QPushButton(F6)
        self.OB44.setGeometry(QtCore.QRect(130, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB44.setFont(font)
        self.OB44.setObjectName("OB44")
        self.OB45 = QtWidgets.QPushButton(F6)
        self.OB45.setGeometry(QtCore.QRect(40, 180, 101, 31))
        self.OB45.clicked.connect(self.switchtoF1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OB45.setFont(font)
        self.OB45.setObjectName("OB45")
        self.OB39 = QtWidgets.QLabel(F6)
        self.OB39.setGeometry(QtCore.QRect(740, 230, 41, 31))
        self.OB39.setStyleSheet("\n"
"background-color: rgb(218, 218, 218);\n"
"border-radius:40px")
        self.OB40.clicked.connect(self.myself)
        self.OB39.setObjectName("OB39")
        self.OB44.clicked.connect(self.switchtoF11)

        self.retranslateUi(F6)
        QtCore.QMetaObject.connectSlotsByName(F6)

    def switchtoF1(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F1()
        self.ui.setupUi(self.window)
        self.F6.close()
        self.window.show()

    def switchtoF11(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F11()
        self.ui.setupUi(self.window)
        self.F6.close()
        self.window.show()

    def myself(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F6()
        self.ui.setupUi(self.window)
        self.F6.close()
        self.window.show()

    def switchtoF8(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F8()
        self.ui.setupUi(self.window)
        self.F6.close()
        self.window.show()

    def retranslateUi(self, F6):
        _translate = QtCore.QCoreApplication.translate
        F6.setWindowTitle(_translate("F6", "Form"))
        self.OB40.setText(_translate("F6", "خانه"))
        self.OB41.setText(_translate("F6", ":امتیاز من"))
        self.OB42.setText(_translate("F6", "ثبت محصول جدید/شارژمجدد محصولات"))
        self.OB43.setText(_translate("F6", "لیست محصولات موجود من"))
        self.OB44.setText(_translate("F6", "کیف پول من"))
        self.OB45.setText(_translate("F6", "خروج از حساب"))
        self.OB39.setText(_translate("F6", "0"))

class Ui_F7(object):
    def setupUi(self, F7):
        self.F7 = F7
        F7.setObjectName("F7")
        F7.resize(900, 585)
        F7.setMinimumSize(QtCore.QSize(900, 585))
        F7.setMaximumSize(QtCore.QSize(900, 585))
        self.pinfo = QtWidgets.QLabel(F7)
        self.pinfo.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.pinfo.setMinimumSize(QtCore.QSize(900, 585))
        self.pinfo.setMaximumSize(QtCore.QSize(900, 585))
        self.pinfo.setText("")
        self.pinfo.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.pinfo.setScaledContents(True)
        self.pinfo.setObjectName("pinfo")
        self.tifo = QtWidgets.QLabel(F7)
        self.tifo.setGeometry(QtCore.QRect(380, 160, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.tifo.setFont(font)
        self.tifo.setObjectName("tifo")
        self.telfo = QtWidgets.QLabel(F7)
        self.telfo.setGeometry(QtCore.QRect(670, 300, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.telfo.setFont(font)
        self.telfo.setObjectName("telfo")
        self.posfo = QtWidgets.QLabel(F7)
        self.posfo.setGeometry(QtCore.QRect(510, 350, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.posfo.setFont(font)
        self.posfo.setObjectName("posfo")
        self.addfo = QtWidgets.QLabel(F7)
        self.addfo.setGeometry(QtCore.QRect(450, 400, 421, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addfo.setFont(font)
        self.addfo.setObjectName("addfo")
        self.Hbtn = QtWidgets.QPushButton(F7)
        self.Hbtn.setGeometry(QtCore.QRect(40, 510, 111, 41))
        self.Hbtn.clicked.connect(self.switchtoF5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Hbtn.setFont(font)
        self.Hbtn.setObjectName("Hbtn")

        self.retranslateUi(F7)
        QtCore.QMetaObject.connectSlotsByName(F7)

    def switchtoF5(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F5()
        self.ui.setupUi(self.window)
        self.F7.close()
        self.window.show()

    def retranslateUi(self, F7):
        _translate = QtCore.QCoreApplication.translate
        F7.setWindowTitle(_translate("F7", "Form"))
        self.tifo.setText(_translate("F7", " ارتباط با ما"))
        self.telfo.setText(_translate("F7", "تلفن: 02188442112"))
        self.posfo.setText(_translate("F7", "پست الکترونیکی: golbarg.shop@yahoo.com"))
        self.addfo.setText(_translate("F7", "  آدرس: خیابان نلسون ماندلا - نرسیده به چهارراه جهان کودک \n"
" ساختمان امیرپرویز - طبقه 9 - واحد 54"))
        self.Hbtn.setText(_translate("F7", "بازگشت به خانه"))

class Ui_F8(object):
    def setupUi(self, F8):
        self.F8 = F8
        F8.setObjectName("F8")
        F8.resize(900, 585)
        F8.setMinimumSize(QtCore.QSize(900, 585))
        F8.setMaximumSize(QtCore.QSize(900, 585))
        self.b_lbl = QtWidgets.QLabel(F8)
        self.b_lbl.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.b_lbl.setMinimumSize(QtCore.QSize(900, 585))
        self.b_lbl.setMaximumSize(QtCore.QSize(900, 585))
        self.b_lbl.setText("")
        self.b_lbl.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.b_lbl.setScaledContents(True)
        self.b_lbl.setObjectName("b_lbl")
        self.add_btn = QtWidgets.QPushButton(F8)
        self.add_btn.setGeometry(QtCore.QRect(630, 150, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("")
        self.add_btn.setObjectName("add_btn")
        self.add_btn.clicked.connect(self.openinfo)
        self.label = QtWidgets.QLabel(F8)
        self.label.setGeometry(QtCore.QRect(670, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.h_btn = QtWidgets.QPushButton(F8)
        self.h_btn.setGeometry(QtCore.QRect(90, 150, 100, 41))
        self.h_btn.clicked.connect(self.switchtoF6)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.h_btn.setFont(font)
        self.h_btn.setObjectName("h_btn")
        self.lst = QtWidgets.QListWidget(F8)
        self.lst.setGeometry(QtCore.QRect(90, 210, 721, 301))
        self.lst.setObjectName("lst")
        self.ed_btn_2 = QtWidgets.QPushButton(F8)
        self.ed_btn_2.setGeometry(QtCore.QRect(390, 150, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ed_btn_2.setFont(font)
        self.ed_btn_2.setObjectName("ed_btn_2")
        self.lst.setCurrentRow(0)
        self.fetchdata()
        self.ed_btn_2.clicked.connect(self.switchtoF14)

        self.retranslateUi(F8)
        QtCore.QMetaObject.connectSlotsByName(F8)

    def fetchdata(self):
        curs.execute("SELECT good_n FROM goods")
        names = curs.fetchall()
        curs.execute("SELECT price FROM goods")
        prices = curs.fetchall()
        curs.execute("SELECT id FROM goods")
        ids = curs.fetchall()
        x = 0
        for i in ids:
            row = self.lst.currentRow()
            self.lst.insertItem(row, f"{i[0]}  ==>  {names[x][0]} ***** {prices[x][0]}تومان")
            x += 1

    def switchtoF6(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F6()
        self.ui.setupUi(self.window)
        self.F8.close()
        self.window.show()

    def switchtoF14(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F14()
        self.ui.setupUi(self.window)
        self.window.show()

    def openinfo(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F9()
        self.ui.setupUi(self.window)
        self.F8.close()
        self.window.show()

    def retranslateUi(self, F8):
        _translate = QtCore.QCoreApplication.translate
        F8.setWindowTitle(_translate("F8", "Form"))
        self.add_btn.setText(_translate("F8", "+"))
        self.label.setText(_translate("F8", "ثبت محصول جدید"))
        self.h_btn.setText(_translate("F8", "بازگشت به خانه"))
        self.ed_btn_2.setText(_translate("F8", "ویرایش"))

class Ui_F9(object):
    def setupUi(self, F9):
        self.F9 = F9
        F9.setObjectName("F9")
        F9.resize(340, 505)
        F9.setStyleSheet(
            "background:qlineargradient(spread:pad, x1:0.239, y1:0.238636, x2:1, y2:1, stop:0 rgba(127, 225, 43, 255), stop:1 rgba(255, 255, 255, 255))")
        self.pi_lbl = QtWidgets.QLabel(F9)
        self.pi_lbl.setGeometry(QtCore.QRect(75, 20, 200, 180))
        self.pi_lbl.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.505682, radius:0.466655, fx:0.5, fy:0.511364, stop:0 rgba(243, 205, 29, 217), stop:1 rgba(255, 255, 255, 255));\n"
            "")
        self.pi_lbl.setText("")
        self.pi_lbl.setScaledContents(True)
        self.pi_lbl.setObjectName("pi_lbl")
        self.up_btn = QtWidgets.QPushButton(F9)
        self.up_btn.setGeometry(QtCore.QRect(120, 220, 101, 30))
        self.up_btn.setStyleSheet("background:None")
        self.up_btn.setObjectName("up_btn")
        self.up_btn.clicked.connect(self.getImage)
        self.lineEdit = QtWidgets.QLineEdit(F9)
        self.lineEdit.setGeometry(QtCore.QRect(30, 265, 211, 28))
        self.lineEdit.setStyleSheet("background:None")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(F9)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 310, 211, 28))
        self.lineEdit_2.setStyleSheet("background:None")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.con_btn = QtWidgets.QPushButton(F9)
        self.con_btn.setGeometry(QtCore.QRect(120, 450, 101, 31))
        self.con_btn.setStyleSheet("background:None")
        self.con_btn.setObjectName("con_btn")
        self.g_name = QtWidgets.QLabel(F9)
        self.g_name.setGeometry(QtCore.QRect(230, 270, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.g_name.setFont(font)
        self.g_name.setStyleSheet("background:None")
        self.g_name.setObjectName("g_name")
        self.prc = QtWidgets.QLabel(F9)
        self.prc.setGeometry(QtCore.QRect(240, 310, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.prc.setFont(font)
        self.prc.setStyleSheet("background:None")
        self.prc.setObjectName("prc")
        self.prc_2 = QtWidgets.QLabel(F9)
        self.prc_2.setGeometry(QtCore.QRect(240, 360, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.prc_2.setFont(font)
        self.prc_2.setStyleSheet("background:None")
        self.prc_2.setObjectName("prc_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(F9)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 355, 211, 28))
        self.lineEdit_3.setStyleSheet("background:None")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(F9)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 400, 171, 28))
        self.lineEdit_4.setStyleSheet("background:None")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.prc_3 = QtWidgets.QLabel(F9)
        self.prc_3.setGeometry(QtCore.QRect(240, 405, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.prc_3.setFont(font)
        self.prc_3.setStyleSheet("background:None")
        self.prc_3.setObjectName("prc_3")
        self.pr_lbl = QtWidgets.QLabel(F9)
        self.pr_lbl.setGeometry(QtCore.QRect(36, 399, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pr_lbl.setFont(font)
        self.pr_lbl.setStyleSheet("background-color:None")
        self.pr_lbl.setObjectName("pr_lbl")
        self.con_btn.clicked.connect(self.datasofgood)

        self.retranslateUi(F9)
        QtCore.QMetaObject.connectSlotsByName(F9)

    def getImage(self):
        self.fname = QFileDialog.getOpenFileName(None, 'Open image...', 'c\\', 'Image files (*.jpg *.jpeg *.png)')
        self.imagePath = self.fname[0]
        self.pixmap = QPixmap(self.imagePath)
        self.pi_lbl.setPixmap(QPixmap(self.pixmap))

    def datasofgood(self):
        # curs.execute("""
        #              CREATE TABLE goods (photo text, good_n text, price integer, num_of_p integer, id integer)
        #  """)
        self.photo_p = self.imagePath
        self.good_n = self.lineEdit.text()
        self.price = self.lineEdit_2.text()
        self.num_of_p = self.lineEdit_3.text()
        self.id = self.lineEdit_4.text()
        curs.execute("INSERT INTO goods (photo, good_n, price, num_of_p, id) VALUES (?, ?, ?, ?, ?)", (self.photo_p, self.good_n, self.price, self.num_of_p, self.id))
        conn.commit()
        self.closemyself()

    def closemyself(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F8()
        self.ui.setupUi(self.window)
        self.F9.close()
        self.window.show()

    def retranslateUi(self, F9):
        _translate = QtCore.QCoreApplication.translate
        F9.setWindowTitle(_translate("F9", "Form"))
        self.up_btn.setText(_translate("F9", "آپلود عکس"))
        self.con_btn.setText(_translate("F9", "ثبت"))
        self.g_name.setText(_translate("F9", "نام جنس:"))
        self.prc.setText(_translate("F9", "قیمت:"))
        self.prc_2.setText(_translate("F9", "موجودی محصول:"))
        self.prc_3.setText(_translate("F9", "شناسه محصول:"))
        self.pr_lbl.setText(_translate("F9", "PR"))

class Ui_F10(object):
    def setupUi(self, F10):
        self.F10 = F10
        F10.setObjectName("F10")
        F10.resize(900, 585)
        F10.setMinimumSize(QtCore.QSize(900, 585))
        F10.setMaximumSize(QtCore.QSize(900, 585))
        self.O1 = QtWidgets.QLabel(F10)
        self.O1.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.O1.setText("")
        self.O1.setPixmap(QtGui.QPixmap("scr2.jpg"))
        self.O1.setScaledContents(True)
        self.O1.setObjectName("O1")
        self.O2 = QtWidgets.QLabel(F10)
        self.O2.setGeometry(QtCore.QRect(360, 20, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.O2.setFont(font)
        self.O2.setObjectName("O2")
        self.O3 = QtWidgets.QLabel(F10)
        self.O3.setGeometry(QtCore.QRect(560, 151, 47, 20))
        self.O3.setObjectName("O3")
        self.O4 = QtWidgets.QLabel(F10)
        self.O4.setGeometry(QtCore.QRect(600, 150, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O4.setFont(font)
        self.O4.setObjectName("O4")
        self.O8 = QtWidgets.QPushButton(F10)
        self.O8.setGeometry(QtCore.QRect(460, 340, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O8.setFont(font)
        self.O8.setObjectName("O8")
        self.O9 = QtWidgets.QPushButton(F10)
        self.O9.setGeometry(QtCore.QRect(40, 520, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O9.setFont(font)
        self.O9.setObjectName("O9")
        self.O9.clicked.connect(self.switchtoF5)
        self.O5 = QtWidgets.QLabel(F10)
        self.O5.setGeometry(QtCore.QRect(600, 220, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.O5.setFont(font)
        self.O5.setObjectName("O5")
        self.O6 = QtWidgets.QLabel(F10)
        self.O6.setGeometry(QtCore.QRect(590, 280, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O6.setFont(font)
        self.O6.setObjectName("O6")
        self.O7 = QtWidgets.QLineEdit(F10)
        self.O7.setGeometry(QtCore.QRect(460, 285, 113, 20))
        self.O7.setObjectName("O7")

        self.retranslateUi(F10)
        QtCore.QMetaObject.connectSlotsByName(F10)

    def switchtoF5(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F5()
        self.ui.setupUi(self.window)
        self.F10.close()
        self.window.show()

    def retranslateUi(self, F10):
        _translate = QtCore.QCoreApplication.translate
        F10.setWindowTitle(_translate("F10", "Form"))
        self.O2.setText(_translate("F10", "     کیف پول من"))
        self.O3.setText(_translate("F10", "0"))
        self.O4.setText(_translate("F10", "موجودی حساب:"))
        self.O8.setText(_translate("F10", "پرداخت "))
        self.O9.setText(_translate("F10", "بازگشت به خانه"))
        self.O5.setText(_translate("F10", "شارژ کیف پول:"))
        self.O6.setText(_translate("F10", "مبلغ قابل پرداخت:"))

class Ui_F11(object):
    def setupUi(self, F11):
        self.F11 = F11
        F11.setObjectName("F11")
        F11.resize(900, 585)
        F11.setMinimumSize(QtCore.QSize(900, 585))
        F11.setMaximumSize(QtCore.QSize(900, 585))
        self.O12 = QtWidgets.QLabel(F11)
        self.O12.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.O12.setText("")
        self.O12.setPixmap(QtGui.QPixmap("scr2.jpg"))
        self.O12.setScaledContents(True)
        self.O12.setObjectName("O12")
        self.O13 = QtWidgets.QLabel(F11)
        self.O13.setGeometry(QtCore.QRect(370, 50, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.O13.setFont(font)
        self.O13.setObjectName("O13")
        self.O14 = QtWidgets.QLabel(F11)
        self.O14.setGeometry(QtCore.QRect(590, 150, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O14.setFont(font)
        self.O14.setObjectName("O14")
        self.O21 = QtWidgets.QPushButton(F11)
        self.O21.setGeometry(QtCore.QRect(40, 520, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O21.setFont(font)
        self.O21.setObjectName("O21")
        self.O22 = QtWidgets.QPushButton(F11)
        self.O22.setGeometry(QtCore.QRect(430, 390, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O22.setFont(font)
        self.O22.setObjectName("O22")
        self.O23 = QtWidgets.QPushButton(F11)
        self.O23.setGeometry(QtCore.QRect(150, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O23.setFont(font)
        self.O23.setObjectName("O23")
        self.O15 = QtWidgets.QLabel(F11)
        self.O15.setGeometry(QtCore.QRect(610, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O15.setFont(font)
        self.O15.setObjectName("O15")
        self.O11 = QtWidgets.QComboBox(F11)
        self.O11.setGeometry(QtCore.QRect(360, 210, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O11.setFont(font)
        self.O11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.O11.setObjectName("O11")
        self.O11.addItem("")
        self.O11.addItem("")
        self.O11.addItem("")
        self.O11.addItem("")
        self.O11.addItem("")
        self.O16 = QtWidgets.QLabel(F11)
        self.O16.setGeometry(QtCore.QRect(570, 280, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.O16.setFont(font)
        self.O16.setObjectName("O16")
        self.O17 = QtWidgets.QLabel(F11)
        self.O17.setGeometry(QtCore.QRect(550, 152, 21, 21))
        self.O17.setObjectName("O17")
        self.O18 = QtWidgets.QLabel(F11)
        self.O18.setGeometry(QtCore.QRect(550, 215, 47, 13))
        self.O18.setObjectName("O18")
        self.O19 = QtWidgets.QLabel(F11)
        self.O19.setGeometry(QtCore.QRect(560, 340, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O19.setFont(font)
        self.O19.setObjectName("O19")
        self.O20 = QtWidgets.QLineEdit(F11)
        self.O20.setGeometry(QtCore.QRect(432, 344, 131, 20))
        self.O20.setObjectName("O20")
        self.O21.clicked.connect(self.switchtoF6)

        self.retranslateUi(F11)
        QtCore.QMetaObject.connectSlotsByName(F11)

    def switchtoF6(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F6()
        self.ui.setupUi(self.window)
        self.F11.close()
        self.window.show()

    def retranslateUi(self, F11):
        _translate = QtCore.QCoreApplication.translate
        F11.setWindowTitle(_translate("F11", "Form"))
        self.O13.setText(_translate("F11", "     کیف پول من"))
        self.O14.setText(_translate("F11", "موجودی حساب:"))
        self.O21.setText(_translate("F11", "بازگشت به خانه"))
        self.O22.setText(_translate("F11", "برداشت"))
        self.O23.setText(_translate("F11", "لیست سفارش های گرفته شده"))
        self.O15.setText(_translate("F11", "درآمد و سود:"))
        self.O11.setItemText(0, _translate("F11", "بازه زمانی را مشخص کنید"))
        self.O11.setItemText(1, _translate("F11", "هفته جاری"))
        self.O11.setItemText(2, _translate("F11", "این ماه"))
        self.O11.setItemText(3, _translate("F11", "امسال"))
        self.O11.setItemText(4, _translate("F11", "درآمد کل"))
        self.O16.setText(_translate("F11", "برداشت از حساب:"))
        self.O17.setText(_translate("F11", "0"))
        self.O18.setText(_translate("F11", "0"))
        self.O19.setText(_translate("F11", "مبلغ:"))

class Ui_F12(object):
    def setupUi(self, F12):
        self.F12 = F12
        F12.setObjectName("F12")
        F12.resize(434, 536)
        F12.setMinimumSize(QtCore.QSize(434, 536))
        F12.setMaximumSize(QtCore.QSize(434, 536))
        F12.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.239, y1:0.238636, x2:1, y2:1, stop:0 rgba(127, 225, 43, 255), stop:1 rgba(255, 255, 255, 255))")
        self.pic_lbl = QtWidgets.QLabel(F12)
        self.pic_lbl.setGeometry(QtCore.QRect(105, 20, 220, 220))
        self.pic_lbl.setScaledContents(True)
        self.pic_lbl.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.505682, radius:0.466655, fx:0.5, fy:0.511364, stop:0 rgba(243, 205, 29, 217), stop:1 rgba(255, 255, 255, 255));\n"
        "border-radius:circle\n"
        "")
        self.pic_lbl.setText("")
        self.pic_lbl.setObjectName("pic_lbl")
        self.name_lbl = QtWidgets.QLabel(F12)
        self.name_lbl.setGeometry(QtCore.QRect(240, 270, 111, 51))
        self.name_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.name_lbl.setText("")
        self.name_lbl.setObjectName("name_lbl")
        self.num_lbl = QtWidgets.QLabel(F12)
        self.num_lbl.setGeometry(QtCore.QRect(240, 370, 111, 51))
        self.num_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.num_lbl.setText("")
        self.num_lbl.setObjectName("num_lbl")
        self.prc_lbl = QtWidgets.QLabel(F12)
        self.prc_lbl.setGeometry(QtCore.QRect(40, 270, 111, 51))
        self.prc_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.prc_lbl.setText("")
        self.prc_lbl.setObjectName("prc_lbl")
        self.id_lbl = QtWidgets.QLabel(F12)
        self.id_lbl.setGeometry(QtCore.QRect(40, 370, 111, 51))
        self.id_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.id_lbl.setObjectName("id_lbl")
        self.add_btn = QtWidgets.QPushButton(F12)
        self.add_btn.setGeometry(QtCore.QRect(130, 450, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_btn.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.add_btn.setObjectName("add_btn")
        self.tprc_lbl = QtWidgets.QLabel(F12)
        self.tprc_lbl.setGeometry(QtCore.QRect(160, 270, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tprc_lbl.setFont(font)
        self.tprc_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tprc_lbl.setObjectName("tprc_lbl")
        self.tid_lbl = QtWidgets.QLabel(F12)
        self.tid_lbl.setGeometry(QtCore.QRect(160, 370, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tid_lbl.setFont(font)
        self.tid_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tid_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tid_lbl.setObjectName("tid_lbl")
        self.tnum_lbl = QtWidgets.QLabel(F12)
        self.tnum_lbl.setGeometry(QtCore.QRect(360, 370, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tnum_lbl.setFont(font)
        self.tnum_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tnum_lbl.setObjectName("tnum_lbl")
        self.tname_lbl = QtWidgets.QLabel(F12)
        self.tname_lbl.setGeometry(QtCore.QRect(360, 270, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tname_lbl.setFont(font)
        self.tname_lbl.setStyleSheet("background-color:rgb(171, 255, 181);\n"
        "border-radius:12px")
        self.tname_lbl.setObjectName("tname_lbl")

        self.retranslateUi(F12)
        QtCore.QMetaObject.connectSlotsByName(F12)

    def catch(self, data):
        self.data = data.split()
        _translate = QtCore.QCoreApplication.translate
        self.name_lbl.setText(_translate("F12", self.data[2]))
        self.id_lbl.setText(_translate("F12", self.data[0]))
        self.prc_lbl.setText(_translate("F12", self.data[4]))
        self.num_lbl.setText(_translate("F12", self.data[6]))
        curs.execute("SELECT photo FROM goods WHERE id = (?)", (self.data[0]))
        pic = curs.fetchone()
        pic = pic[0]
        print(pic)
        self.pixmap = QPixmap(pic)
        self.pic_lbl.setPixmap(QPixmap(self.pixmap))


    def retranslateUi(self, F12):
        _translate = QtCore.QCoreApplication.translate
        F12.setWindowTitle(_translate("F12", "Form"))
        self.add_btn.setText(_translate("F12", "افزودن به سبد خرید"))
        self.tprc_lbl.setText(_translate("F12", "  قیمت:"))
        self.tid_lbl.setText(_translate("F12", " شناسه:"))
        self.tnum_lbl.setText(_translate("F12", "  تعداد:"))
        self.tname_lbl.setText(_translate("F12", "  نام:"))

class Ui_F13(object):
    def setupUi(self, F13):
        self.F13=F13
        F13.setObjectName("F13")
        F13.resize(900, 585)
        F13.setMinimumSize(QtCore.QSize(900, 585))
        F13.setMaximumSize(QtCore.QSize(900, 585))
        self.backg = QtWidgets.QLabel(F13)
        self.backg.setGeometry(QtCore.QRect(0, 0, 900, 585))
        self.backg.setText("")
        self.backg.setPixmap(QtGui.QPixmap("scr1.jpg"))
        self.backg.setScaledContents(True)
        self.backg.setObjectName("backg")
        self.title = QtWidgets.QLabel(F13)
        self.title.setGeometry(QtCore.QRect(380, 150, 121, 101))
        font = QtGui.QFont()
        font.setFamily("Urdu Typesetting")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.listWidget = QtWidgets.QListWidget(F13)
        self.listWidget.setGeometry(QtCore.QRect(20, 280, 841, 171))
        self.listWidget.setObjectName("listWidget")
        self.sabt = QtWidgets.QPushButton(F13)
        self.sabt.setGeometry(QtCore.QRect(390, 500, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sabt.setFont(font)
        self.sabt.setObjectName("sabt")
        self.return_2 = QtWidgets.QPushButton(F13)
        self.return_2.setGeometry(QtCore.QRect(20, 500, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.return_2.setFont(font)
        self.return_2.setObjectName("return_2")
        self.return_2.clicked.connect(self.switchtoF5)

        self.retranslateUi(F13)
        QtCore.QMetaObject.connectSlotsByName(F13)

    def switchtoF5(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_F5()
        self.ui.setupUi(self.window)
        self.F13.close()
        self.window.show()

    def retranslateUi(self, F13):
        _translate = QtCore.QCoreApplication.translate
        F13.setWindowTitle(_translate("F13", "Form"))
        self.title.setText(_translate("F13", "سبد خرید"))
        self.sabt.setText(_translate("F13", "ثبت و پرداخت"))
        self.return_2.setText(_translate("F13", "بازگشت به خانه"))

class Ui_F14(object):
    def setupUi(self, F14):
        self.F14=F14
        F14.setObjectName("F14")
        F14.resize(434, 536)
        F14.setMinimumSize(QtCore.QSize(434, 536))
        F14.setMaximumSize(QtCore.QSize(434, 536))
        F14.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.239, y1:0.238636, x2:1, y2:1, stop:0 rgba(127, 225, 43, 255), stop:1 rgba(255, 255, 255, 255))")
        self.O51 = QtWidgets.QLabel(F14)
        self.O51.setGeometry(QtCore.QRect(105, 20, 220, 220))
        self.O51.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.505682, radius:0.466655, fx:0.5, fy:0.511364, stop:0 rgba(243, 205, 29, 217), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:circle\n"
"")
        self.O51.setText("")
        self.O51.setObjectName("O51")
        self.O52 = QtWidgets.QLabel(F14)
        self.O52.setGeometry(QtCore.QRect(280, 300, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O52.setFont(font)
        self.O52.setStyleSheet("background-color:rgb(171, 255, 181);\n"
"border-radius:12px")
        self.O52.setObjectName("O52")
        self.O53 = QtWidgets.QLabel(F14)
        self.O53.setGeometry(QtCore.QRect(260, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O53.setFont(font)
        self.O53.setStyleSheet("background-color:rgb(171, 255, 181);\n"
"border-radius:12px")
        self.O53.setObjectName("O53")
        self.O56 = QtWidgets.QPushButton(F14)
        self.O56.setGeometry(QtCore.QRect(190, 470, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.O56.setFont(font)
        self.O56.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.O56.setObjectName("O56")
        self.O54 = QtWidgets.QLineEdit(F14)
        self.O54.setGeometry(QtCore.QRect(110, 305, 113, 31))
        self.O54.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.O54.setObjectName("O54")
        self.O55 = QtWidgets.QLineEdit(F14)
        self.O55.setGeometry(QtCore.QRect(110, 395, 113, 31))
        self.O55.setStyleSheet("background-color:rgb(171, 255, 181);")
        self.O55.setObjectName("O55")

        self.retranslateUi(F14)
        QtCore.QMetaObject.connectSlotsByName(F14)

    def retranslateUi(self, F14):
        _translate = QtCore.QCoreApplication.translate
        F14.setWindowTitle(_translate("F14", "Form"))
        self.O52.setText(_translate("F14", "قیمت:"))
        self.O53.setText(_translate("F14", "تعداد موجود:"))
        self.O56.setText(_translate("F14", "ثبت تغییرات"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    F1 = QtWidgets.QWidget()
    ui = Ui_F1()
    ui.setupUi(F1)
    F1.show()
    sys.exit(app.exec_())